<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class TaskTest extends TestCase
{
    use DatabaseTransactions;
    protected $task;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->task = factory(\App\Task::class)->create();

    }

    /** @test*/
    public function it_sets_a_task_to_complete()
    {
        $this->assertFalse($this->task->completed);

        $this->task->complete();

        $this->assertTrue($this->task->completed);
    }

    /** @test*/
    public function it_sets_a_task_to_uncomplete()
    {
        $this->assertFalse($this->task->completed);

        $this->task->complete();

        $this->assertTrue($this->task->completed);

        $this->task->incomplete();

        $this->assertFalse($this->task->completed);
    }
}
